FROM node:22-alpine

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=384"

COPY package*.json ./

RUN npm ci --legacy-peer-deps

COPY . .

EXPOSE 4200

CMD ["npm", "start", "--", "--host", "0.0.0.0"]

