services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"   # Angular Dev Server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--max-old-space-size=384
    mem_limit: 512m

