services:
  firebase-emulators:
    build:
      context: .
      dockerfile: firebase/Dockerfile.firebase
    ports:
      - "4000:4000"   # Emulator UI Dashboard
      - "8080:8080"   # Firestore Emulator
      - "9099:9099"   # Auth Emulator
    volumes:
      - ./firebase.json:/app/firebase.json
      - ./firestore.rules:/app/firestore.rules
      - ./firestore.indexes.json:/app/firestore.indexes.json

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"   # Angular Dev Server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - firebase-emulators
