FROM node:20-alpine

# Install OpenJDK 21 for Firestore emulator support & bash
RUN apk add --no-cache openjdk21-jre bash

# Install Firebase CLI globally
RUN npm install -g firebase-tools

WORKDIR /app

EXPOSE 4000 8080 9099

CMD ["firebase", "emulators:start", "--project=organizador-cursada-demo", "--config=firebase.json"]
