name: CI & Deployment Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate production environment configuration
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_USER_POOL_ID: ${{ secrets.AWS_USER_POOL_ID }}
          AWS_USER_POOL_WEB_CLIENT_ID: ${{ secrets.AWS_USER_POOL_WEB_CLIENT_ID }}
          AWS_COGNITO_OAUTH_DOMAIN: ${{ secrets.AWS_COGNITO_OAUTH_DOMAIN }}
          AWS_REDIRECT_SIGN_IN: ${{ secrets.AWS_REDIRECT_SIGN_IN }}
          AWS_REDIRECT_SIGN_OUT: ${{ secrets.AWS_REDIRECT_SIGN_OUT }}
          AWS_API_ENDPOINT: ${{ secrets.AWS_API_ENDPOINT }}
        run: npm run config:env

      - name: Build Angular Application
        run: npm run build
